// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Graffiti",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "Graffiti",
            targets: ["AppModule"],
            bundleIdentifier: "com.kyoya.Graffiti",
            teamIdentifier: "3X7LEN654Y",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .magicWand),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ],
            capabilities: [
                .camera(purposeString: "For AR"),
                .photoLibraryAdd(purposeString: "To save photos and videos"),
                .microphone(purposeString: "Unknown Usage Description")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)